//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furnish
{
    using System;
    using System.Collections.Generic;
    using System.Data.SqlTypes;
    using System.Windows.Media;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string imageUrl { get; set; }
        public decimal price { get; set; }
        public int qtyAvailable { get; set; }

        

        //public ImageSource image { get; set; }

        public Product(string _name, string _description, string _imageUrl, decimal _price, int _qtyAvailable)
        {
            this.name = _name;
            this.description = _description;
            this.imageUrl = _imageUrl;
            this.price = _price;
            this.qtyAvailable = _qtyAvailable;
        }

        public Product(string _name, string _description, decimal _price, int _qtyAvailable)
        {
            this.name = _name;
            this.description = _description;
            this.price = _price;
            this.qtyAvailable = _qtyAvailable;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
