//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furnish
{
    using System;
    
    public enum StatusEnum : int
    {
        InPreparation = 1,
        Paid = 2
    }
}
